#!/bin/bash
source /root/build-config.sh
source /root/build-common.sh
check_vars

if [[ -z "$1" ]]; then
	echo "Please supply version number"
	exit
else
	VERSION=$1
fi

function cleanup(){
	# Remove stale wine sockets
	rm -rf /tmp/.wine-*
}

cleanup

SOURCEDIR=/opt/wine-electrum/drive_c/electrum-oracoin/Electrum-Oracoin-$VERSION


cd $SOURCEDIR

$PYTHON "C:/PyInstaller/pyinstaller.py" -y "C:/electrum-oracoin/deterministic.spec"
cp /opt/wine-electrum/drive_c/electrum-oracoin/electrum-oracoin.nsi $SOURCEDIR/

echo "Running c:/electrum-oracoin/Electrum-Oracoin-$VERSION/electrum-oracoin.nsi for install"
xvfb-run wine c:\\"Program Files"\\NSIS\\makensis.exe -V1 c:/electrum-oracoin/Electrum-Oracoin-$VERSION/electrum-oracoin.nsi


cleanup
test -d /root/release-packages/Windows || mkdir -pv /root/release-packages/Windows
mv /opt/wine-electrum/drive_c/electrum-oracoin/Electrum-Oracoin-${VERSION}/dist/electrum-oracoin-setup.exe /root/release-packages/Windows/Electrum-Oracoin-${VERSION}-Windows-setup.exe
mv /opt/wine-electrum/drive_c/electrum-oracoin/Electrum-Oracoin-${VERSION}/dist/electrum-oracoin.exe /root/release-packages/Windows/Electrum-Oracoin-${VERSION}-Windows.exe
